# Generated by Django 6.0 on 2026-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_sample_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario GitHub'),
        ),
    ]
