# Generated by Django 6.0 on 2026-01-20 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_github_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Competencia',
                'verbose_name_plural': 'Competencias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='Lograda')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_competencies', to='attendance.competency', verbose_name='Competencia')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_competencies', to='attendance.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Competencia del Estudiante',
                'verbose_name_plural': 'Competencias de Estudiantes',
                'unique_together': {('student', 'competency')},
            },
        ),
    ]
