# Generated by Django 6.0 on 2026-01-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_real_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name_normalized', 'first_name'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AddField(
            model_name='student',
            name='last_name_normalized',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
