# Generated by Django 6.0 on 2026-01-27 17:28

from django.db import migrations


def add_emails(apps, schema_editor):
    """Añadir correos electrónicos a los estudiantes especificados."""
    Student = apps.get_model('attendance', 'Student')
    
    emails = {
        ("Juan Manuel", "Flórez Robledo"): "jmflorezr@eafit.edu.co",
        ("Alexandra", "Hurtado David"): "ahurtadod@eafit.edu.co",
        ("Isabella", "Idárraga Botero"): "iidarragab@eafit.edu.co",
    }
    
    for (first_name, last_name), email in emails.items():
        Student.objects.filter(first_name=first_name, last_name=last_name).update(email=email)


def remove_emails(apps, schema_editor):
    """Eliminar correos electrónicos de los estudiantes (reversión)."""
    Student = apps.get_model('attendance', 'Student')
    
    students = [
        ("Juan Manuel", "Flórez Robledo"),
        ("Alexandra", "Hurtado David"),
        ("Isabella", "Idárraga Botero"),
    ]
    
    for first_name, last_name in students:
        Student.objects.filter(first_name=first_name, last_name=last_name).update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_add_missing_students'),
    ]

    operations = [
        migrations.RunPython(add_emails, remove_emails),
    ]
